### ISSUE TITLE
Multiple Zutaten für einen Rezeptschritt

### ISSUE THREAD

**Issue by honigwald** [honigwald/rathsnetz#1]
Aktuell kann nur eine Zutat für einen Schritt eines Rezepts ausgewählt werden. Es müssen aber Mehrere ausgewählt werden können.

**Comment by honigwald** [comment]
Brauchen wir das hier noch?

**Comment by honigwald** [comment]
@Bu5ch3 brauchen wir das noch?

**Comment by Bu5ch3** [comment]
Naja gelöst ist es nicht, man muss sich weiterhin durch mehrere Schritte durchklicken. Ist aber nicht wahnsinnig schlimm.
