### ISSUE TITLE
Zutatenliste

### ISSUE THREAD

**Issue by honigwald** [honigwald/rathsnetz#11]
Als Vorbereitung für den Braugang muss eine Liste von benötigten Zutaten kalkuliert werden.
Hierbei muss der Lagerbestand berücksichtigt werden.

**Comment by Bu5ch3** [comment]
Folgende Angaben wären mEn relevant (Beispiel):

Wasser | Hauptguss (Leitungswasser) | 96 | l
-- | -- | -- | --
  | Nachguss (Leitungswasser) | 84 | l
  |   |   |  
Malz | Wiener Malz | 27000 | g
  | Sauermalz | 3000 | g
  |   |   |  
I Hopfengabe | Hallertauer Mittelfrüh 3,4% | 160 | g
II Hopfengabe | Bäkehopfen | 120 | g
  |   |   |  
Hefe | Mangrove Jack's Bavarian Lager Yeast -M76- | 3 | Packungen

**Comment by honigwald** [comment]
implementiert.
