### ISSUE TITLE
"iSpindel Laden" als Vorbereitung

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#12]
Wenn ich einen BRaugang startet, will ich daran erinnert werden, die iSpindel zu laden.

**Comment by honigwald** [comment]
Aktuell können Vorarbeiten über das Admin UI gepflegt werden (hinzufügen, bearbeiten, löschen). 
Die Frage ist: Soll/Muss das über das Frontend gepflegt werden oder reicht es diese (mehrheitlich einmaligen) Arbeiten über das Admin UI zu erledigen?

**Comment by Bu5ch3** [comment]
Admin ui reicht. Wie genau komme ich da hin? Dann könnte ich es selber erledigen.

**Comment by honigwald** [comment]
https://braurat.de/trunk/admin
![image](https://user-images.githubusercontent.com/38533378/103416013-ed10ce80-4b84-11eb-97fd-347783a6cc6c.png)
