### ISSUE TITLE
Neue Lager Kategorien manuell erstellen

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#13]
Möglichkeit neue Kategorien zu erstellen sollte evtl. allen Nutzern möglich sein? (Szenario: Experimentales Brauen mit einer neuen Zutat wie Milchsäure)

![image](https://user-images.githubusercontent.com/76732377/103342440-c883fc00-4a89-11eb-9212-cf870a93dcdd.png)

**Comment by Bu5ch3** [comment]
lösen wir über admin, wenn nötig
