### ISSUE TITLE
Anzeigen von Inventar bei <0 mit rotem Text.

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#14]
Anzeigen von Inventar bei <0 mit rotem Text um klarzustellen dass hier nachgekauft werden muss.

**Comment by honigwald** [comment]
Mein Vorschlag:
Für jeden Artikel im Lager werden Grenzwerte definiert. Wird der Wert unterschritten, dann taucht der Artikel in einer extra Liste "Zu beschaffene Artikel" auf.

Außerdem werde ich die Artikel so umstellen, dass die Menge nicht mehr <0 sinken kann.

**Comment by honigwald** [comment]
Ich habe es jetzt wie zuvor erwähnt implementiert. Jeder Artikel kann nun so konfiguriert werden (True/False), dass er bei erreichen von Grenzwert 1 als Warnung (Gelb) und bei Grenzwert 2 als Kritisch (Rot) angezeigt wird.

![image](https://user-images.githubusercontent.com/38533378/104129188-f875ae00-536b-11eb-8d53-22b7360ca9bd.png)
