### ISSUE TITLE
Steps verschwinden aus der angezeigten Liste aber bleiben offen im Dropdown

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#16]
Steps verschwinden aus der angezeigten Liste aber bleiben offen im Dropdown

![image](https://user-images.githubusercontent.com/76732377/103343004-409ef180-4a8b-11eb-95eb-82870d1ed729.png)

**Comment by honigwald** [comment]
Was bedeutet das konkret?
Meinst du mit "offener Liste" die Kette der Rezeptschritte? Im Dropdown Menu bleiben die Schritte immer sichtbar, damit man diese wieder immer wieder in die Kette der Rezeptschritte einhaengen kann.

**Comment by maexchen2048** [comment]
Ich meinte dass der zu erstellende Step nicht in der tabellarischen Auflistung selbst bleibt nachdem er angelegt wurde (mit Fehler also z.b fehlende Mengenangabe). In diesem Fall ist er nur im Dropdown zu sehen sind nicht aber in der eigentlichen Rezeptauflistung darunter als nummerierter Step.

**Comment by honigwald** [comment]
Die einzelnen Rezeptschritte werden nur in der Rezeptliste (unten) geführt, wenn der Schritt korrekt in die Liste eingehangen wurde. Wird ein Schritt nicht einsortiert bzw. besitzt er keine Zuordnung, dann wird dieser Schritt über der Rezeptliste also unzugeordnet aufgeführt. So kann man den Schritt nachträglich in die Liste einhängen.

Im aktuellen PreRelease funktioniert das einhängen und verschieben von einsortierten Schritten noch nicht ganz fehlerfrei. Dieser BUG hier sollte, aber keiner sein bzw. ist schon behoben.

Ich schließe den Issue.
