### ISSUE TITLE
Korrektur eines Rezeptes führt zu kritischem Error

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#18]
Korrektur Wirlpool zu Whirlpool im Hellem Urrezept war über bearbeiten des Rezeptes nicht möglich und führte zu Server Error.

![image](https://user-images.githubusercontent.com/76732377/103343125-8e1b5e80-4a8b-11eb-8c9e-5820ee08410d.png)

**Comment by honigwald** [comment]
Duplicate of #24
