### ISSUE TITLE
Server Error beim Erstellen einer Charge

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#19]
Server Error beim Erstellen einer Charge "Samisches Korn" parallel zu einer bereits aktiven Charge. Auch klicken auf die offene Charge Samisches Korn (202012.7) führt zu einem Server Error.

![image](https://user-images.githubusercontent.com/76732377/103343222-e5b9ca00-4a8b-11eb-81f4-ffc05df7c477.png)

**Comment by honigwald** [comment]
Ich hab es mal debuggt. Der Error kommt, weil das Rezept einige (möglw. extra) eingebaute Fehler hatte.
u.a. Zutat ohne Menge, Menge ohne Zutat usw.

Hier muss entweder bei der Pflege des Rezepts darauf geachtet werden oder es muss von Anfang an verhindert werden. Letzteres muss implementiert werden.

Ps: Die aktiven Chargen "Samisches Korn" können jetzt beendet werden.

**Comment by honigwald** [comment]
Das Speichern von Zutaten ohne Menge ODER Mengen ohne Zutaten ist jetzt nicht mehr möglich. Damit sollte dieser Bug gelöst sein.
