### ISSUE TITLE
Option hinzufügen Chargen zu löschen

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#20]
Gibt es eine Option die Charge zu löschen? Habe mittlerweile drei aktive die bei einem Server Error landen

**Comment by honigwald** [comment]
Ich würde sagen eine Löschen Option für Chargen sollte es über das Frontend nicht geben. Im Admin UI kann man die Chargen löschen.

**Comment by honigwald** [comment]
Da hier nichts mehr kommt, gehe ich davon aus, dass die Pflege über das Backend ausreicht.
