### ISSUE TITLE
Option einen Schritt ohne Notizen abzuschließen 

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#21]
Müssen Notizen erstellet werden um einen Schritt abzuschließen? Option das Feld leer zu lassen sollte gegeben sein.

![image](https://user-images.githubusercontent.com/76732377/103343422-51039c00-4a8c-11eb-97cd-00a343f10c1a.png)

**Comment by honigwald** [comment]
Aktuell ist das Feld ein MUSS. Wir können es so umstellen, dass das Feld auch leer sein darf.

**Comment by honigwald** [comment]
@Bu5ch3 was meinst du dazu? Mir persönlich ist es gleich. Wenn das Feld ein muss ist, dann ist gewährleistet, dass es nicht übersehen wird. Wenn man nichts notieren will, dann reicht ja ein "Alles erledigt" o.ä.

**Comment by Bu5ch3** [comment]
Also beim Brauen von Charge C202101.1 zu 90% händisch "done" eingetippt habe. Es ist also definitiv optional. Allerdings habe ich #27 eröffnet, weil die Eingabemaske einfach zu klein ist, wenn man sie denn doch benutzen möchte. Beides lässt sich im Protokoll ganz gut sehen:
https://braurat.de/trunk/brewing/protocol/17/

**Comment by honigwald** [comment]
Okay, dann stelle ich das Feld auf "Optional" um.

**Comment by honigwald** [comment]
erledigt.
