### ISSUE TITLE
Rezeptschritt verliert Zuordnung

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#24]
Wenn ich einen Rezeptschritt bearbeitet habe und diese Änderung speichere, dann wird sie zwas übernommen, der Schritt verliert aber seine Zuördnung, obwohl diese nicht verändert wurde.
Erwartung wäre, dass diese bestehen und der Schritt zugeordnet bleibt.

**Comment by honigwald** [comment]
Die gesamte Pflege der Rezepte wurde überarbeitet. Einzelne Schritte können hin- und hergeschoben werden, Neue eingepflegt werden und Änderungen vorgenommen werden. Hierbei aktualisiert sich das Rezept inklusive der Schrittnummern automatisch.

Vorerst konnte ich keine neuen Fehler generieren.

**Comment by Bu5ch3** [comment]
Das Problem wurde nicht behoben. Der Schritt verliert weiterhin seine Zuordnung, wenn ich ihn editiere.
