### ISSUE TITLE
"Vorarbeiten" besser beschreiben

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#25]
Aktuell ist die Zeichenanzahl der Describtion für die Vorbereitungen sehr begränzt. Es wäre gut, wenn ein Text wie der Nachfolgende dort abgebildet werden könnten:

Pumpe reinigen:

_Den Kochtopf mit Wasser füllen, so das der Abflusshahn komplett überflutet ist. Das Wasser auf deutlich über 80°C erhitzen. Den gesamten track kurz mit dem heißen Wasser spülen und in einen Beählter Umpumpen, damit das erster verunreinigte Wasser nicht wieder im Kochtopf landet. Danach das heiße Wasser für ca 10min im Kreis wieder in den Kochtopf pumpen. Am Ende das Wasser gänzlich abpumpen und den Topf für den Braugang vorbereiten. Dieser Vorgang ist wichtig, damit das alles hygienisch rein ist, wenn später das Bier durch die Anlage zur Gärung gepumpt wird._

**Comment by honigwald** [comment]
Feld geändert: 50 -> 600 Zeichen.
