### ISSUE TITLE
"Nächster Schritt" anzeigen

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#29]
Während des Brauens wäre es gut auch den nächsten Schritt bereits sehen zu können. Das ist hilfreich um alles entsprechend vorzubereiten bzw. ein letztes Mal zu prüfen, ob alles bereit steht.

**Comment by maexchen2048** [comment]
Am besten wäre es alle Schritte des Rezeptes bereits angepasst auf die eigentliche menge des Brauvorganges sichtbar zu haben. Die noch kommenden Schritte z.b als grauer Text. So kann der Brauer sich schonmal anschauen wieviel Hopfen z.b für die Zielmenge abgewogen werden muss.

**Comment by honigwald** [comment]
done.
