### ISSUE TITLE
Darstellung von "Lager" übersichtlicher machen

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#30]
Ich würde mir wünschen, dass man im Lager grundsätzlich Hopfen, Malz und Hefe in separaten Tabellen darstellt und diese Listen dann Alphabetisch sortiert. Würde mir das für den First Release wünschen, wenn nicht zu aufwendig.

**Comment by honigwald** [comment]
Duplicate of #10
