### ISSUE TITLE
"Kalkulierte Zutaten" verschwindet

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#32]
Wenn ich eine neue Charge anlege und dann im Schritt "Vorbereiten bin, dort die Haken NICHT alle gemacht habe aber auf "Weiter" klicke, dann verschwindet die Zutatenliste. Man kann zwar über die Browserhistory zurück gehen, aber das ist irgendwie verwirrend. Vielleicht sollte "Weiter" nicht klickbar/ aktiv sein, bis das passiert ist.

**Comment by honigwald** [comment]
Kann ich bestätigen. Der Schritt verliert seinen Kontext, dass ist schnell gefixt. Werde mich die Tage darum kümmern.

**Comment by honigwald** [comment]
fixed.
