### ISSUE TITLE
Fehler beim erstellen eines neuen Rezeptes

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#36]
Ich wollte schonmal das Rezept für das Weizen nach Hermannverfahren anlegen. Brautermin ist der 13 Februar (Experimentelles Brauen).  Hiebei taucht folgender Felher auf nach dem das Rezept fur 100 Liter berechnet wird.

Ich bin eingeloggt als "basti"

![image](https://user-images.githubusercontent.com/76732377/105634384-03e1d280-5e5e-11eb-919c-1aac0797f0f8.png)

![image](https://user-images.githubusercontent.com/76732377/105634338-d137da00-5e5d-11eb-9624-b2b8d85dcfd4.png)

**Comment by honigwald** [comment]
Fixed.
