### ISSUE TITLE
Wasser als Zutat einfügen

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#38]
Derzeit werden nicht die Mengen des benötigten Wassers (Hauptguss / Nachguss angezeigt). Diese im Rezept skalierbar abzulegen ist nicht möglich da dafür Wasser als Zutat/Inventar vorhanden sein müsste. Dies wäre essentiell und sollte gleich als erster Schritt im Rezept stehen.

**Comment by maexchen2048** [comment]
Hat sich eigentlich erledigt. Habe Wasser als Zutat mit 1 Milliarde Litern im Lager angelegt und jetzt kann man das auch im Rezept reflektieren.

**Comment by maexchen2048** [comment]
Back vielleicht checkst du nochmal ob das so wie oben am besten gelöst ist.

**Comment by Bu5ch3** [comment]
Hauptguss und Nachguss sollten auch nach Abschluss des Braugangs im Protokoll (Header) angezeigt werden.

**Comment by honigwald** [comment]
> Hat sich eigentlich erledigt. Habe Wasser als Zutat mit 1 Milliarde Litern im Lager angelegt und jetzt kann man das auch im Rezept reflektieren.

Das ergibt keinen Sinn. HG/NG werden jetzt beim Brauen dauerhaft angezeit. Ausserdem sind die Werte in jedem Rezept hinterlegt, insofern muss Wasser nicht im Lager geführt werden.

**Comment by honigwald** [comment]
> Hauptguss und Nachguss sollten auch nach Abschluss des Braugangs im Protokoll (Header) angezeigt werden.

done.
