### ISSUE TITLE
Erfassung der Sudhausbeute / Alkoholgehalt / Bierfarbe

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#39]
Automatische Berechnung von Sudhausaubseute / Alkoholghealt und evtl Bierfarbe.
Falls im Brauprotokoll eine Eingabe  vorliegt (sollte obligatorisch sein bei Stammwürze Messung und dann nach Abschluss der Gärung) können diese recht leicht berechnet werden und in der fertigen charge abgespeichert werden.

Falls so weit können wir uns zusammen die Formeln anschauen.

**Comment by maexchen2048** [comment]
Dieser Schritt wäre die Voraussetzung für #41

**Comment by honigwald** [comment]
Wie können die Parameter berechnet werden?

**Comment by maexchen2048** [comment]
Sudhausausbeute steht hier:
https://www.maischemalzundmehr.de/index.php?inhaltmitte=toolssudhausausbeute

Alkoholgehalt hier:
https://www.maischemalzundmehr.de/index.php?inhaltmitte=toolsspindelrechner

**Comment by Bu5ch3** [comment]
![image](https://user-images.githubusercontent.com/76428911/156992637-de162251-ef7c-4c71-bae4-1ca4b935b2bf.png)
http://fabier.de/biercalcs.html
*push*

Ich fände es gut, wenn wir zumindest den Alkoholgehalt für jede Charge errechnen. Wir haben ja schon die Angabe EVG am Ende des Brauganges. Wir bräuchten nur dasselbe auch vor Beginn der Gärung und schon hätten wir die Daten um die Berechnung vorzunehmen.
Ein positiver Nebeneffekt dessen könnte auch sein, dass es dann immer auch eine Schnellprobe gibt, wenn dieser Wert vor der Gärung gemessen werden muss.

**Comment by honigwald** [comment]
Der Bug #42 sollte im Rahmen dieses Tickets gefixt werden.

So wie ich es verstehe brauchen wir vor und nach der Gärung eine Stammwürze-Messung (inkl. Temperatur-Angabe).
Mit dem Ergebenis kann dann EVG (scheinbar, tatsächlich), Restextrakt (scheinbar, tatsächlich) und Alkoholgehalt autom. berechnet werden.

**Comment by Bu5ch3** [comment]
Ich würde #42 auch schließen. EVG ist mir persönlich tatsächlich egal und wurde auch als Begriff falsch eingebracht.
Mein Ziel ist es für jeden Braugang den Alkoholgehalt zu wissen. Dafür muss die Stammwürze einmal direkt nach dem Anstellen und einmal nach dem Ende der Gärung gemessen werden, wie oben in dem Rechner gezeigt. Daraus errechnet sich der Alkoholgehalt. EVG und Restextrakt sind aus meiner Sicht (aktuell) nicht relevant

**Comment by honigwald** [comment]
done.
