### ISSUE TITLE
Wasservorbereitung als Teil des Rezeptes

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#40]
Vorbereitung des Brauwassers (skaliert) für den jeweiligen Biertyp. Hierbei sollte für jedes Rezept die passenden Zutaten hinterlegt und eingetragen werden (Miclhsäure/Sauermalz/Phosphorsäure/Braukalk etc.).

Somit müssen wir nicht jedes mal neu experimentieren und dieses recht komplexe Thema könnte mit einmaligen justieren auf 100L adressiert werden.

**Comment by honigwald** [comment]
Brauchen wir das hier noch?
