### ISSUE TITLE
Digitale Etiketten

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#41]
Falls alle relevanten #39 Brauparameter erfasst sind könnten wir ein Digitales Etikett zu jeder Charge erstellen. Im Idealfall so dass man es auch gleich für den eigentlichen Druck verwenden kann.

**Comment by honigwald** [comment]
Die Drucken-Funktion wird vorerst hinten angestellt. Stattdessen wird es einen QR Code geben, der einen Link zum Protokoll generiert. Der QR Code kann dann auf die Flasche.

**Comment by honigwald** [comment]
done in Version >= 2.2.0
