### ISSUE TITLE
EVG ins DP

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#42]
Endvergärungsgrad muss vor abschließen des Gärvorgangs eingetragen werden

**Comment by honigwald** [comment]
done.

**Comment by honigwald** [comment]
Wir benutzen EVG anders, als er definiert ist
![image](https://user-images.githubusercontent.com/38533378/158054206-b6ec7934-089f-4655-aa84-2862054db1f1.png)
Quelle: https://hobbybrauer.de/forum/wiki/doku.php/endvergaerungsgrad

@Bu5ch3 Welcher EVG soll ins Protokoll (scheinbar / tasächlich / beide / keiner)?

**Comment by honigwald** [comment]
Da beide EVGs nur berechnet werden kann, wurde dieser nun entfernt. An seine Stelle kommt der Restextrakt, der durch Spindel ermittelt wird. Der EVG kann hiermit berechnet werden.
