### ISSUE TITLE
Bierblick bearbeiten und Eintrag löschen über einen Knopf

### ISSUE THREAD

**Issue by maexchen2048** [honigwald/rathsnetz#48]
Beim Bierblick müssen derzeit zum korrekten Löschen bzw. Nullen eines Fasses alle Felder manuell geleert werden. Hier wäre eine Funktion wie "Leeren / Löschen" sinnvoll.

![image](https://user-images.githubusercontent.com/76732377/112957055-5c289f80-9141-11eb-8466-e4117729bc53.png)

**Comment by honigwald** [comment]
Ist schon implementiert.
![image](https://user-images.githubusercontent.com/38533378/141695219-4cbd3b46-28c4-48c9-abd4-90c57d69ed40.png)

**Comment by maexchen2048** [comment]
Danke für das schließen des Themas ist gelöst.
