### ISSUE TITLE
[BUG] Bottom navigation bar verdeckt Content

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#50]

**Comment by honigwald** [comment]
Kann ich so auch nachstellen
![image](https://user-images.githubusercontent.com/38533378/141957449-59c518c1-c3f3-40a9-9f5a-f1e3dafef177.png)

**Comment by honigwald** [comment]
Lösung: .container-content { heigth: 85% -> 100%}

**Comment by honigwald** [comment]
Fixed in _refactor21_
