### ISSUE TITLE
"Master" Hopfen in Ur-Rezepten

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#52]
...

**Comment by Bu5ch3** [comment]
Aktuell basieren alle Rezepte auf einem Eintrag im Lager. Wird dieser Eintrag im Lager editiert, ändert sich das entsprechend im Rezept.
Problemszenario:
* jemand aktualisiert den Lagerbestand nach dem Eintreffen einer neuen Lieferung.
* es gibt zwei Einträge mit "Saazer" Hopfen im Lager (Saazer 3,0% & Saazer 4,0%)
* "Saazer 4,0%" hat noch einen Restbestand
* "Saazer 3,0%" ist komplett leer (ist aber Master für das Ur-Rezept)
* die neue Lieferung beinhaltet X-g "Saazer 3,6%"

Die Person entscheidet sich den Eintrag "Saazer 3,0%" einfach zu ändern und den Alphasäurewert der neuen Lieferung anzupassen. 3,0% wird zu 3,6%
-> Das Ur-Rezept beinhaltet nun "Saazer 3,6%" ohne, dass eine Anpassung der Mengen erfolgt

Daraus können weitreichende Änderungen in den Rezepten Einzug halten, ohne, dass es bemerkt wird.

mögliche Lösungen:
* Die Ur-Rezepte basieren auf Werten, die nicht editierbar/ sichtbar sind
* Die Lagereinträge, die als Master gelten, werden "gesperrt"

**Comment by honigwald** [comment]
Die nachträgliche Änderung der Alphasäure ist jetzt deaktiviert.
