### ISSUE TITLE
Zutatenwarnungen neue Charge

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#53]
Vorgehen:
* Vor anlegen der Charge wurde Lagerbestände angepasst mit Augenmerk auf die Hopfensorten.
* * Zwei Hopfensorten sind in ausreichender Menge aber mit abweichenden Säuregehältern vorhanden
* * Ein Hopfen ist gar nicht im Lager vorhanden
* Charge wird mit 100l angelegt
* Folgende Maske erscheint:
* 
![Warnungen in Chargenmaske](https://user-images.githubusercontent.com/76428911/150118729-5180081a-3be9-4e39-9131-5864556e47af.png)

* Für die beiden Hopfen werden die alternativen korrekt umgerechnet und vorgeschlagen (Ich würde auf Nachkommastellen verzichten, aber das ist Geschmackssache)
* Für "Saazer 3,0%" gibt es keine Alternative, da das Lager leer ist
* Nun wir der Lagerbestand für "Saazer 7,0%" auf 100g geändert.
-> Erwartung wäre, dass bei erneutem Laden der Chargen-Seite nun auch der alternative Hopfen mit der entsprechenden Umrechnung erscheint. Dies ist nicht der Fall

* Braugang wird durchgeführt

* * auch wärend des Braugangs wird keine Umrechnung vorgenommen:
* 
*  ![Hopfen](https://user-images.githubusercontent.com/76428911/150120889-d811535a-bad7-40c4-88de-fb036fe08ae3.png)

* Nach Abschluss des Braugangs werden die Lagerbestände abgeglichen: 
![Lagervergleich](https://user-images.githubusercontent.com/76428911/150120964-ca63b599-4f3f-4c8e-b7a7-0c60ad15d95a.png)
-> Alle Einträge außer dem Hopfen sind korrekt.

**Comment by honigwald** [comment]
@Bu5ch3 
Der Hopfenrechner läuft einmalig beim Anlegen der Charge. Falls sich der Lagerbestand ändert, dann muss der Rechner über den Knopf neugestartet werden. Probier mal, ob du so zu dem richtigen Ergebnis kommst.

**Comment by Bu5ch3** [comment]
@honigwald ah, den Knopf habe ich übersehen, obwohl der ziemlich groß ist...

**Comment by Bu5ch3** [comment]
@honigwald Okay der Button macht das Ticket hier überflüssig!
