### ISSUE TITLE
Analyse-Tab

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#54]
Grundsätzlich finde ich die Idee und den aktuellen Stand sehr gut.
Hier einige Anmerkungen:

Beim Bierblick würde ich mir eine Art Auslastung wünschen. Das bedeutet ich möchte gerne sehen, wie viel vom gesamten Lagervolumen aktuell genutzt wird.

![image](https://user-images.githubusercontent.com/76428911/150125061-702f9843-8bdd-4ba3-a787-bd353815213a.png)

Bei der Bierbalance würde ich mir eine zeitliche Betrachtung über mehrere Monate hinweg wünschen.

![image](https://user-images.githubusercontent.com/76428911/150125260-ece359c4-a2c1-4789-84f0-2897db9d0741.png)

Geld i/o
Idee gefällt mir. Würde ich aber von dieser ANsicht entkoppeln und eigenständig machen. Zudem müsste man sicher noch Funktionalitäten ergänzen, damit das operativ einen Wert entfaltet

![image](https://user-images.githubusercontent.com/76428911/150125478-97a618a3-2689-42a0-b8fb-399c6abdfcc6.png)

**Comment by honigwald** [comment]
Die Anmerkungen wurden implementiert.
