### ISSUE TITLE
Sortierung Bierblick

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#55]
Ich fände es gut, wenn wir im Zuge des nächsten Release noch die Sortierung der Bieliste fixen könnten. Wenn ich nach "Keg/Inhalt" sortiere, dann wird immer nach den Zahlen und nicht nach dem Inhalte bzw. Alphabet sortiert. Eine Lösung könnte sein, dass man beide Zeilen trennt und eine für die NR. und eine für den Inhalt halt. Das würde das Prblem in meinen Augen schon lösen und das ganze deutlich brauchbarer machen.

**Comment by honigwald** [comment]
Erste Spalte wurde in zwei gesplittet.
