### ISSUE TITLE
Findings from Release 2.2.2

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#69]
PDF Protokoll.
* "Bäkrebräu" Logo ist weiß auf weiß. Das Schwarze wäre hier günstiger
* Im "Brauprotokoll" fehlen die "Notizen". Es wäre wünschenswert diese auch zu sehen

QR-Code:
* funktioniert gut. Link ist auch über inkognito-Fenster abrufbar. Evtl. könnte man hier darüber nachdenken lediglich die PDF-Variante des Protokolls auszugeben. Sollte man diese Infos öffenlich machen (Etikett) dann sollte man darüber nachdenken

Digitale Etiketten
* siehe QR-Code

Erfassung der Sudhausbeute / Alkoholgehalt / Bierfarbe
* Ist Buggy. Wir erheben (MMuM folgend) "Stammwürze" und "SRE". Diese werden in den Formeln nicht korrekt verarbeitet. Da müssen wir nochmal ran!

**Comment by honigwald** [comment]
Hi @Bu5ch3 
bezüglich des PDF-Protokolls. Hier schreibst du 
> Im "Brauprotokoll" fehlen die "Notizen". Es wäre wünschenswert diese auch zu sehen

und hier
> [...] darüber nachdenken lediglich die PDF-Variante des Protokolls auszugeben

Ich würde es auch okay finden, wenn wir nur ein PDF für die Öffentlichkeit zur Verfügung stellen. Ich meine mich zu Erinnern, dass wir allerdings die Notizen Spalte nicht Öffentlich machen wollen. Damit wäre dann der erste Punkt obsolet oder?

**Comment by honigwald** [comment]
related to #71
