### ISSUE TITLE
"Charge" zurück in den "Bierblick?

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#73]
![image](https://github.com/honigwald/rathsnetz/assets/76428911/18554272-6b56-4511-81f5-88e2ac7f614b)

Wir hatten jetzt wiederholt die Situation mehrere Chargen des gleichen Biestils zu haben. Im Bierblick wäre es in diesen Fällen hilfreich die Charge des jeweiligen Kegs zu sehen. Daraus könnte man ableiten, welche zuerst verbraucht/abgefüllt werden sollten.

**Comment by honigwald** [comment]
Macht Sinn. Ich mache mich dran

**Comment by honigwald** [comment]
:heavy_check_mark:
