### ISSUE TITLE
"Reset" endet in 500er

### ISSUE THREAD

**Issue by Bu5ch3** [honigwald/rathsnetz#74]
Wenn ich in dem Detail-View eines einzelnen Kegs bin und "reset" klicke, dann lande ich auf einem 500er.

Gewünschtes Verhalten:
1. Klick Reset
2. [optional] pop-up: wirklich resetten? [Ja | Nein]
3. Nein -> pop-up zu und zurück zu Keg-View
4. Ja : Content = Leer | Status = "Leer" | Notes = Leer | Filling = Leer

-

**Comment by honigwald** [comment]
hotfixed in version >= 2.2.3
