### ISSUE TITLE
Testing for release

### ISSUE THREAD

**Issue by honigwald** [honigwald/rathsnetz#9]
Folgende Tests müssen vor der ersten Benutzung durchgeführt werden

- [x] Lagerobjekt anlegen/bearbeiten/löschen
- [x] Rezept anlegen/bearbeiten/löschen
- [x] Braugang anlegen. Workflow bis zur fertigen Charge durchführen
- [x] LdeB: Charge in Kegs abspeichern etc.

Sobald alle Tests für gut befunden sind, ist der Milestone erreicht.

**Comment by Bu5ch3** [comment]
### Quick summary:
Test succes rate
100% Lagerobjekt anlegen/bearbeiten/löschen
65% Rezept anlegen/bearbeiten/löschen
90% Braugang anlegen. Workflow bis zur fertigen Charge durchführen
10% LdeB: Charge in Kegs abspeichern etc.

### Testscenario:

Helles Urrezept anlegen, brauen und abfüllen inkl. aller notwendigen Zutaten.

### Lagerobjekt anlegen/bearbeiten/löschen

**Hat alles Problemlos geklappt**

Anmerkungen:

- Sortierung der Gesamten Liste sollte mEn zumindest alphabetisch sortiert sein. Eine weitere Untergliederung nach Typ wäre zudem der besseren Übersichtlichkeit dienlich
- Wenn man ein neues Item anlegt, also neue Zutaten einlager, wäre es cool bei dem Erstellen auch ein Datum zu vergeben. Dann wüsste man also, wie lange die jeweilige Zutat im Lager ist. Daraus ließen sich Schlüsse zur Haltbarkeit ziehen.

### Rezept anlegen/bearbeiten/löschen

**Anlegen:**
- Rezept Anlegen wurde abgebrochen, da kein Item in die Liste mehr angefügt werden konnte
- Schritte Anlegen ist etwas fummelig, weil "prev" nicht automatisch per default auf den letzten Eintrag gesetzt wird. Außerdem gibt es mehrere Schritte die eigentlich den gleichen Titel haben (z.B. Aufheizen). Diese muss man "Aufheiten 1" etc. nennen, damit man erkennen kann, welcher Schritt gemeint ist.
- Beim erstellen der Schritte fehlt eine Temperaturangabe!
- Multi-Select bei den Zutaten wäre gut, weil oft gleich mehrere Sorten Malz oder Hopfen zugegeben werden.
- Beim dritten Schritt komme ich nicht weiter, da ich zwar auf speichern drücken kann, der Schritt aber nicht in der Liste auftaucht. Habe diverse Formatierungen versucht z.B. ganz ohne Zahlen, alle Felder ausgefüllt...alles ohne Erfolg ![image](https://user-images.githubusercontent.com/76428911/102810597-4d08b780-43c4-11eb-91cd-62ec399e6218.png) 

**Bearbeiten:**
- Wenn ich einen Schritt bearbeite, nichts ändere und wieder abspeichere, verliert er seine Zuordnung, obwohl diese im Dropdown vorher angezeigt wird.
- Konnte das Rezept nicht löschen. Warnmeldung wurde bestätigt aber dann ohne Wirkung.
- Wenn ich in diesem Schritt die Temperatur wie nachfolgend eingebe...
![image](https://user-images.githubusercontent.com/76428911/102811704-0f0c9300-43c6-11eb-8cac-282df9cc3a34.png)kommt folgender Fehler...
![image](https://user-images.githubusercontent.com/76428911/102811743-251a5380-43c6-11eb-8067-669b220e41ec.png)



Anmerkungen:

- "_Das Rezept skaliert automatisch. Hiefür muss das Rezept zwingend für 100 Liter eingepflegt werden._" "Hierfür" Rechtschreibung korrigieren. Außerdem sollte hier klargestellt werden, dass es sich um 100l **Ausschlagsmenge** handelt.
- Liste der Vorarbeiten sollte etwas konkreter formuliert werden. Außerdem müsste man hier evtl. weiter ergänzen. (z.B. pH-Wert einstellen)

### Braugang anlegen. Workflow bis zur fertigen Charge durchführen

**Während des Brauens:**

- Timer wäre nice to have
- Läuft ansonsten gut.
- 

**Braugang abschließen**

- Ich weiß nicht wie. Sollte das hier in der Ansicht irgendwo sein?
![image](https://user-images.githubusercontent.com/76428911/102812248-fe105180-43c6-11eb-8c57-fa8f7d7927ea.png)


### LdeB: Charge in Kegs abspeichern etc.

- Obwohl ich den Braugang nicht ordentlich fertiggestellt habe, kann ich die Charge in der Liste finden...
![image](https://user-images.githubusercontent.com/76428911/102812639-a1f9fd00-43c7-11eb-8a08-7efa819fc91e.png)...nach dem Speichern taucht allerdings der Eintrag nicht in der Liste auf...

**Comment by Bu5ch3** [comment]
@honigwald bei Fragen zu meinem Test-Protokoll einfach melden ;)

**Comment by Bu5ch3** [comment]
Ich habe das Problem in der Rezepterstellung gefunden:

Das Format für den Input bei "Duration" muss 00:00:00 sein bzw. wenn man nur "7" eingibt, dann macht er 00:00:07 draus. Ich bekomme es allerdings nicht in 00:07:00 geändert. Er verliert dann wieder seine Zuordnung under der Wert wird auch nicht gespeichert.

Update 2:

Wenn man den Wert für Sekunden eingibt, dann geht es. z.B. 3900 für 65min. Wenn ich allerdings einen Schritt editiere und einen solchen Wert dort eingebe, bekomme ich einen 500er. Der Wert wird allerdings gespeichert und wenn ich erneut zum Rezept navigiere ist auch alles so, wie gewollt.

**Comment by Bu5ch3** [comment]
Habe das Urrezept jetzt vervollständigt. Es fällt auf, dass das REzept etwas unübersichtlich ist. Es könnte schon helfen, wenn alle leeren Daten felder auf leer wären und dort nicht "None" stehen würde.
![image](https://user-images.githubusercontent.com/76428911/102816125-c658d800-43cd-11eb-90e8-40b8e1beaa3d.png)

**Comment by maexchen2048** [comment]
**Zusammenfassung**
Kudos an Backe erstmal in Summe für mich ein **sehr gelungener Ansatz**.

- (+) Strukturiert und logisch aufgebaut
- (+) Kurze Eingewöhnungszeit
- (+) Spiegelt alle Elemente des bisherigen analogen/excel basierten Ansatzes wieder
- (+) Optionen in einer 2.0 Version noch weiter auszubauen (Parameter Berechnung EBU, Alkoholgehalt etc)

- (-) Noch einige kritische Bugs (Server Error, siehe unten)
- (-)Viele Änderungen/Anpassungen nur über Admin möglich

**Lagerobjekt anlegen/bearbeiten/löschen**

- Möglichkeit neue Kategorien zu erstellen sollte evtl. allen Nutzern möglich sein? (Szenario: Experimentales Brauen mit einer neuen Zutat wie Milchsäure)

![image](https://user-images.githubusercontent.com/76732377/103280082-c8bfc100-49cf-11eb-9a4e-8470655afcc7.png)

- Anzeigen von Inventar bei <0 mit rotem Text.


**Rezept anlegen/bearbeiten/löschen**

- Sprachgemisch aus Englisch/Deutsch
- Möglichkeit beim aktuellem den nächsten Schritt schon anzuzeigen? (Geht zur Not auch über seperates Rezept Tab)
- Step Prev. bei Schritt 1 nicht klar

![image](https://user-images.githubusercontent.com/76732377/103280467-c90c8c00-49d0-11eb-8b04-3e7f593ae6ea.png)

- Hatte einen Schritt erstellt der dann aber verloren ging in der Übersicht. Dennoch ist er abrufbar im Prev. Step

![image](https://user-images.githubusercontent.com/76732377/103281537-4cc77800-49d3-11eb-8507-c36e24b76cda.png)

- Einheiten (L, g etc sollten im Rezept mit angezeigt werden direkt nach der Anzahl

![image](https://user-images.githubusercontent.com/76732377/103281763-07577a80-49d4-11eb-8efd-8622df910edb.png)

- Korrektur Wirlpool zu Whirlpool im Hellem Urrezept war über bearbeiten des Rezeptes nicht möglich und führte zu Server Error.

![image](https://user-images.githubusercontent.com/76732377/103282962-93b76c80-49d7-11eb-96c9-400caa3e506a.png)


**Braugang anlegen. Workflow bis zur fertigen Charge durchführen**

- Server Error beim Erstellen einer Charge "Samisches Korn" parallel zu einer bereits aktiven Charge

![image](https://user-images.githubusercontent.com/76732377/103282262-813c3380-49d5-11eb-8598-a9baf00cc092.png)

- Gibt es eine Option die Charge zu löschen? Habe mittlerweile drei aktive die bei einem Server Error landen
- Müssen Notizen erstellet werden um einen Schritt abzuschließen? Option das Feld leer zu lassen sollte gegeben sein.

![image](https://user-images.githubusercontent.com/76732377/103282449-19d2b380-49d6-11eb-9b06-8052c00d0926.png)

- Ansonsten beim Brauen mit dem Hellen Urrezept keine weiteren Probleme. 
- iSpindel abschnitt nicht ganz klar hier solte vielleicht per Notiz mehr Information angezeigt werden

![image](https://user-images.githubusercontent.com/76732377/103283425-d6c60f80-49d8-11eb-94c2-25bda2f219a2.png)

**Comment by honigwald** [comment]
closed.
